server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/psy_db
    username: psy_user
    password: psy_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true

app:
  jwt:
    secret: change-me-super-long-secret-key-for-hs256
    expiration-ms: 86400000
  ollama:
    base-url: http://localhost:11434
    model: qwen2.5:7b
